### ISSUE TITLE
More languages?

### ISSUE THREAD

**Issue by andrekaa** [stefan-it/hmByT5#1]
Would it be possible/interesting to add more languages?
I can provide data for Norwegian.

Andre

**Comment by stefan-it** [comment]
Hi @andrekaa ,

thanks for reaching out!

Currently, I want to use the same languages/corpora as used for our [hmBERT](https://arxiv.org/abs/2205.15575) and additionally include Dutch (from Delpher corpus). But adding e.g. Norwegian would be interesting as well!

Do you have a kind of dataset/corpus description for Norwegian? And do you know if there are some downstream tasks available to test the model?

**Comment by andrekaa** [comment]
Hi @stefan-it ,

there are datasets in the making for downstream tasks for historical NER for Norwegian. And there is even more training data that is freely available. Is it possible to maybe have a talk over Zoom or similar, maybe?

**Comment by stefan-it** [comment]
Hi @andrekaa ,

sounds great! I'm very excited to see Norwegian NER datasets for historic domain :hugs: Definitely, please write me an email (`stefan@schweter.it`) so that we can set-up a call!
